# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MonitorData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MonitorData.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n#com.twtsoft.link.common.model.protoB\020MonitorDataProto'),
  serialized_pb=_b('\n\x11MonitorData.proto\"x\n\x0bMonitorData\x12\r\n\x05\x62oxNo\x18\x01 \x01(\t\x12$\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x16.MonitorData.NameValue\x12\x0c\n\x04time\x18\x03 \x01(\t\x1a&\n\tNameValue\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB7\n#com.twtsoft.link.common.model.protoB\x10MonitorDataProtob\x06proto3')
)




_MONITORDATA_NAMEVALUE = _descriptor.Descriptor(
  name='NameValue',
  full_name='MonitorData.NameValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MonitorData.NameValue.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='MonitorData.NameValue.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=141,
)

_MONITORDATA = _descriptor.Descriptor(
  name='MonitorData',
  full_name='MonitorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boxNo', full_name='MonitorData.boxNo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='MonitorData.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='MonitorData.time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MONITORDATA_NAMEVALUE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=141,
)

_MONITORDATA_NAMEVALUE.containing_type = _MONITORDATA
_MONITORDATA.fields_by_name['data'].message_type = _MONITORDATA_NAMEVALUE
DESCRIPTOR.message_types_by_name['MonitorData'] = _MONITORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MonitorData = _reflection.GeneratedProtocolMessageType('MonitorData', (_message.Message,), dict(

  NameValue = _reflection.GeneratedProtocolMessageType('NameValue', (_message.Message,), dict(
    DESCRIPTOR = _MONITORDATA_NAMEVALUE,
    __module__ = 'MonitorData_pb2'
    # @@protoc_insertion_point(class_scope:MonitorData.NameValue)
    ))
  ,
  DESCRIPTOR = _MONITORDATA,
  __module__ = 'MonitorData_pb2'
  # @@protoc_insertion_point(class_scope:MonitorData)
  ))
_sym_db.RegisterMessage(MonitorData)
_sym_db.RegisterMessage(MonitorData.NameValue)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
